public class HelloWorld{
    
    /*private void sayWhat(string messageText){
        
        string messageDesc = '';
		Account obj = new Account();
        
        contact con = new contact();
       
        boolean status = false;
        if(status){
            
        }
        
        boolean bstatus = false;
        
        double dd;
        dd.longValue();
        
        //processrequest req;
        
        
        CaseFeed dde;
        
        
        
    }
    
    private void sayWhatA(string messageText){
        
        boolean messageDesc = false;
        
    }*/

}